server:
  port: 8080

spring:
  sleuth:
    enabled: false
  zipkin:
    enabled: false
  application:
    name: cloud-order-service
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #cloud:
  #  zookeeper:
  #    connect-string: 192.168.171.127:2181

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver        #mysql驱动包
    url: jdbc:mysql://192.168.171.127:3306/boot-seed?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  instance:
    # 显示服务的名称
    instance-id: oreder-service
    # 点击显示ip
    prefer-ip-address: true
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka #单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版