server:
  port: 8005

spring:
  application:
    name: cloud-consul-service
  cloud:
    consul:
      host: 192.168.171.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}