server:
  port: 7001

spring:
  sleuth:
    enabled: false
    zipkin:
      enabled: false
# EurekaServerAutoConfiguration
eureka:
  instance:
    hostname: eureka7001.com
  server:
    enable-self-preservation: true #默认是true
  client:
    fetch-registry: false
    register-with-eureka: false #不注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
